<?php
/**
 * @file
 * Code for the intervention feature.
 */

include_once 'intervention.features.inc';

/**
 * Implementation of hook_form_FORM_ID_alter
 *
 * Add JavaScript to "node/add/intervention." Add help text to node title.
 */
function intervention_form_intervention_node_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'intervention') . '/js/validation.js';
  drupal_add_js($path);

  $form['title']['#description'] = t('A short title for the intervention');
}

/**
 * Implementation of hook_clone_node_alter().
 */
function intervention_clone_node_alter(&$node, $context) {

  $orig = $context['original_node'];
  if ($orig->type == 'intervention') {
    // re-use original title; i.e., don't prepend "clone of"
    $node->title = $orig->title;

    // increment the reporting year by one
    $year = (int) substr($orig->field_reporting_year[LANGUAGE_NONE][0]['value'], 0, 4);
    $node->field_reporting_year[LANGUAGE_NONE][0]['value'] = ++$year . '-01-01 00:00:00';

    $node->log = "Cloned from {$orig->nid} (revision {$orig->vid}) by {$node->name}";

    // delete moderation data from old node and replace with our own
    unset($node->workbench_moderation);
    $node->workbench_moderation_state_new = 'draft';
    $node->workbench_moderation_state_current = 'draft';
  }
}

/**
 * Implements hook_views_api().
 */
function intervention_views_api() {
  return array("api" => "3.0");
}